spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: "{cipher}AQCPM3iV5oWD7aK2HqLSqtlvm8n7qgKjCU+2bY/fQimC7yf/1lr4xfSiB19Q+YdNaCo2NCInyZ5gKniyPxSAQvT/iaIMlPyquNcCLsUdgae/K6Gnd2zXgbPaRE5y1lLFljpb0CDH4Gbo5qAi7jyOM9b40L/JlaOcYgD5xJpRrpK19JeeJMpVd9aG3tUUx3tVrQ8p1NrwWHxzrvKAkCNn69T13iBKzJAOgBYrL5pmdc9GSAJpn5l7FNbkx1bgCfZbX8+p3M7ZfFEu616BAT98WeXKx10Kw5nZY7JAdB+2nQSOhCMsAdGan6nR7RvPr2uIOSUVqHwmDYucm3VGbgK0JT0vhV+MmOk15giCWi+I8aPvp4I9akyqWZs6NVXF4ylpkEc="

# token:
#   expiration_time: 86400000
#   secret_key: "{cipher}AQCQ/G4mc/dvTUL7xFxFlTex/bA+kIOmszDkipcKoGeWLhx7GSQ79d1YBFUIff6GZ3mWgP7RI6rcYsT6oIzOYSEfAq1UzqnlY28KeBoEJLtTgH+CXQ4wctW5NfVMds2MaK1kek3ULLUBxSRiK+0Q6B0mhkGoOZV/xgsFyRn0gvf5w0GSeZ2ECvJQFznp/OSTJqtPRoX7BxNqc8safIsA7BNubqnLUCNJmpA/gbHVlBMtPRApmNDtD5KAVD/5tKBFkz9fA2Fn9NV09taV7eJl3hDMvYqIVR1G7Wb7InSDcMUrCyQsr+S3who84lGzGS7ux2YG6z6I3+YztgNKRr2oWDC+mvfFjnM3FI71spEDpWDfYON99yUwpbogctDYEcnNTIBv1eFCttCLj4zSwSLU/HoN"

gateway:
  ip: 192.168.0.4

order_service:
  # url: http://127.0.0.1:8000/order-service/%s/orders
  url: http://order-service/order-service/%s/orders # @LoadBalanced 를 통해 ip가 아닌 microservice name으로 접근 가능
  exception:
    order_is_empty: No order Items.
